AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: poja-compute-only - Computation and API

Globals:
  Function:
    CodeUri: .
    Runtime: java21
    Tracing: Active
    Architectures:
      - x86_64
    EventInvokeConfig:
      MaximumRetryAttempts: 0
    AutoPublishAlias: live
    SnapStart:
      ApplyOn: PublishedVersions
    VpcConfig:
      SecurityGroupIds:
        - !Sub '{{resolve:ssm:/poja/sg/id}}'
      SubnetIds:
        - !Sub '{{resolve:ssm:/poja/subnet/private1/id}}'
        - !Sub '{{resolve:ssm:/poja/subnet/private2/id}}'
    Environment:
      Variables:
        ENV: !Ref Env
        AWS_EVENTBRIDGE_BUS: !Sub '{{resolve:ssm:/poja-compute-only/${Env}/eventbridge/bus-name}}'
        AWS_EVENT_STACK_1_SQS_QUEUE_URL: !Sub '{{resolve:ssm:/poja-compute-only/${Env}/1/sqs/mailbox-queue-url}}'
        AWS_EVENT_STACK_2_SQS_QUEUE_URL: !Sub '{{resolve:ssm:/poja-compute-only/${Env}/2/sqs/mailbox-queue-url}}'
        AWS_SES_SOURCE: lou@hei.school
        
        
        
        

Parameters:
  Env:
    Type: String

Resources:
  FrontalServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
        - "*~1*"

  FrontalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.company.base.ApiEventHandler::handleRequest
      MemorySize: 256
      Timeout: 30
      Role: !Sub '{{resolve:ssm:/poja-compute-only/${Env}/execution/role-arn}}'
      
      Events:
        ApiCall:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: FrontalServerlessRestApi
      ReservedConcurrentExecutions: 50

  WorkerFunction1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.company.base.MailboxEventHandler::handleRequest
      MemorySize: 512
      Timeout: 300 #note(sqs-visibility)
      Role: !Sub '{{resolve:ssm:/poja-compute-only/${Env}/execution/role-arn}}'
      
      Events:
        AllEvents:
          Type: SQS
          Properties:
            Queue: !Sub '{{resolve:ssm:/poja-compute-only/${Env}/1/sqs/mailbox-queue-arn}}'
            BatchSize: 1
      ReservedConcurrentExecutions: 50

  WorkerFunction2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.company.base.MailboxEventHandler::handleRequest
      MemorySize: 512
      Timeout: 300 #note(sqs-visibility)
      Role: !Sub '{{resolve:ssm:/poja-compute-only/${Env}/execution/role-arn}}'
      
      Events:
        AllEvents:
          Type: SQS
          Properties:
            Queue: !Sub '{{resolve:ssm:/poja-compute-only/${Env}/2/sqs/mailbox-queue-arn}}'
            BatchSize: 1
      ReservedConcurrentExecutions: 50

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

  ApiUrlSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ /poja-compute-only/, !Ref Env, /api/url ] ]
      Type: String
      Value: !Sub "https://${FrontalServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !GetAtt ApiUrlSSM.Value
