openapi: '3.0.2'
info:
  title: Poja Compute Only
  version: 'latest'
servers:
  - url: https://preprod.hei.school

paths:
  /ping:
    get:
      tags:
        - Health
      operationId: ping
      responses:
        '200':
          description: pong
          content:
            text/plain:
              schema:
                type: string
                example: pong